version: "2"
services:
  node:
    image: "node:10"
    user: "node"
    working_dir: /app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/app
    expose:
      - "443"
    command: "npm start"
